services:
  db:
    image: postgres:16-alpine
    container_name: fitmetrics_db
    restart: always
    environment:
      POSTGRES_USER: fit_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fitmetrics
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: